### PR TITLE
feat -> changed compile to implementation

### PR DESCRIPTION
**Pull request by rgarciadelongoria**
resolve issue #34 

change deprecated compile to implementation

Error with compile:

Captura de Pantalla 2022-08-02 a las 11 48 30

### CODE REVIEW

**Comment by Ziao** [comment]
Can this be merged? This is working.
Using your branch for now. Thanks dude <3

**Comment by rgarciadelongoria** [comment]
> Can this be merged? This is working.
> Using your branch for now. Thanks dude <3

Yes dude, I use this on my own projects.

Waiting for the PR on this repo.

**Comment by sneko** [comment]
@SenNeonoveNoci @pavel-kroh-smartlook also thinking it should be merged :)

**Comment by SenNeonoveNoci** [comment]
@rgarciadelongoria @sneko @Ziao 
I'm so sorry that it took us this long to merge this PR. We had some changes in our team that affected this.

I have merged this and I want to ensure you that we will work on this plugin and update all the deprecated stuff in the upcoming weeks.

Thank you for your patience.

František Spurný
Lead mobile developer

**Comment by wsamoht** [comment]
Can we get a new version tagged so this is included on npm?

**Pull request merged**
