### PR TITLE
iOS update

### PR DESCRIPTION
**Pull request by pavel-kroh-smartlook**

### CODE REVIEW

**Comment by Maransatto** [comment]
Hi, after this update I can't compile anymore, after run ```ionic cordova build ios``` even after removing the platform and adding it again.

Does someone have some suggestion?

image

**Comment by pavel-kroh-smartlook** [comment]
@Maransatto pity the error log says no details about why it could not compile. Could you open terminal at `platforms/ios/` and run `pod cache clean --all; pod update; cat Podfile.lock` to see if Smartlook 1.3.0 is properly installed?

**Comment by Maransatto** [comment]
Thank you @pavel-kroh-smartlook 
The command you asked me to run fixed it.

image

**Comment by pavel-kroh-smartlook** [comment]
@Maransatto great! It seems that albeit the Smartlook Cordova plugin states its dependency on our native iOS SDK, it does unfortunately not update it automatically when new version of the native SDK is released. These command-line instructions could be handy with other iOS libraries as well.

**Pull request merged**
